# Generated by Django 2.0 on 2018-12-22 03:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('comment_text', models.CharField(max_length=500, verbose_name='内容')),
                ('comment_date', models.CharField(max_length=50, verbose_name='日期')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '歌曲评论',
                'verbose_name_plural': '歌曲评论',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_plays', models.IntegerField(verbose_name='播放次数')),
                ('dynamic_search', models.IntegerField(verbose_name='搜索次数')),
                ('dynamic_down', models.IntegerField(verbose_name='下载次数')),
            ],
            options={
                'verbose_name': '歌曲动态',
                'verbose_name_plural': '歌曲动态',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=32, verbose_name='歌手名字')),
                ('singer_sex', models.ImageField(choices=[('1', '男'), ('2', '女')], default=1, upload_to='', verbose_name='歌手性别')),
                ('siger_country', models.IntegerField(choices=[('1', '大陆'), ('2', '港台'), ('3', '岛国'), ('4', '欧美')], default=1, verbose_name='歌手国籍')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌曲序号')),
                ('song_name', models.CharField(max_length=32, verbose_name='歌曲名字')),
                ('song_time', models.CharField(max_length=10, verbose_name='时长')),
                ('song_album', models.CharField(max_length=50, verbose_name='专辑')),
                ('song_languages', models.CharField(max_length=20, verbose_name='语种')),
                ('song_type', models.CharField(max_length=20, verbose_name='类型')),
                ('song_release', models.DateField(default=datetime.datetime.now, verbose_name='发行时间')),
                ('song_img', models.ImageField(upload_to='img/%Y%m', verbose_name='歌曲图片')),
                ('song_lyrics', models.FileField(upload_to='file/%Y%m', verbose_name='歌词')),
                ('song_file', models.FileField(upload_to='file/%Y%m', verbose_name='歌曲文件')),
            ],
            options={
                'verbose_name': '歌曲信息',
                'verbose_name_plural': '歌曲信息',
            },
        ),
        migrations.CreateModel(
            name='SongLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('label_name', models.CharField(max_length=32, verbose_name='分类标签')),
            ],
            options={
                'verbose_name': '歌曲分类',
                'verbose_name_plural': '歌曲分类',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.SongLabel', verbose_name='歌名分类'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Singer', verbose_name='歌手'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='歌曲'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song', verbose_name='歌名'),
        ),
    ]
