# Generated by Django 2.0 on 2018-12-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singer',
            old_name='siger_country',
            new_name='singer_country',
        ),
    ]
