# Generated by Django 2.0 on 2018-12-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181222_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_image',
            field=models.ImageField(default='music/static/image/datu-1.jpg', upload_to='image/%Y%m', verbose_name='歌手招聘'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_sex',
            field=models.IntegerField(choices=[('1', '男'), ('2', '女')], default=1, verbose_name='歌手性别'),
        ),
    ]
