# Generated by Django 2.0 on 2018-12-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181222_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_country',
            field=models.IntegerField(choices=[('1', '大陆'), ('2', '港台'), ('3', '岛国'), ('4', '欧美')], verbose_name='歌手国籍'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_sex',
            field=models.IntegerField(choices=[('1', '男'), ('2', '女')], verbose_name='歌手性别'),
        ),
    ]
