# Generated by Django 2.0 on 2018-12-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181222_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_country',
            field=models.CharField(choices=[('1', '大陆'), ('2', '港台'), ('3', '岛国'), ('4', '欧美')], max_length=100, verbose_name='歌手国籍'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=100, verbose_name='歌手性别'),
        ),
    ]
