# Generated by Django 2.0 on 2018-12-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181222_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_image',
            field=models.ImageField(blank=True, default='music/static/image/datu-1.jpg', null=True, upload_to='image/%Y%m', verbose_name='歌手照片'),
        ),
    ]
