# Generated by Django 2.0 on 2018-12-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181222_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_time',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_type',
        ),
    ]
