# Generated by Django 2.0 on 2018-12-22 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181222_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.CharField(default=datetime.datetime.now, max_length=100, verbose_name='日期'),
        ),
    ]
